### ISSUE TITLE
Cannot login to WebUI using Ubuntu Focal image on Raspberry Pi 4 (Raspbian)

### ISSUE THREAD

**Issue by tyron** [linuxserver/docker-qbittorrent#104]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When launching the login UI and providing the username and password, it should allow me to login.

## Current Behavior

When I click the "Login" button, my browser just redirects to the same page. The content of `http://<my-ip>:8080/` after the call to `http://<my-ip>:8080/api/v2/auth/login` is exactly the same as the unauthenticated version. If I provide incorrect username/password, the UI indicates the error.
This is happening with Ubuntu 20.04.1 (Focal) image only -- when testing against 18.04.1, it works fine.

![image](https://user-images.githubusercontent.com/186183/107999208-e1eaf400-6fb4-11eb-87f6-97e2b885b4a8.png)

## Steps to Reproduce

1. Update dockerfile on my Raspberry Pi 4 to run from a Ubuntu Focal image
2. Launch web ui
3. Provide username and password
4. Get redirect to the login page again

## Environment
**OS:** Raspbian (`Linux raspberrypi 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux`)
**CPU architecture:** arm32
**How docker service was installed:** From official repo, with `curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh`

## Command used to create docker container (run/create/compose/screenshot)

_docker-compose.yaml_
```yaml
version: "3.4"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:arm32v7-14.3.3.99202101191832-7248-da0b276d5ubuntu20.04.1-ls115
    container_name: qbittorrent
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/qbittorrent:/config # config files
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
    networks: # appropriate IP for outbound is configured on qbittorrent config
      macvlan-v10:
        ipv4_address: xxx # interface used as outbound from container
      macvlan-wan:
        ipv4_address: yyy # IP used to access on the internal network

```

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
You are using a legacy method of defining umask
please update your environment variable from UMASK_SET to UMASK
to keep the functionality after July 2021
[services.d] done.
QWaitCondition::wait(): cv wait failure: Invalid argument
QWaitCondition::wait(): cv wait failure: Invalid argument
```
