### ISSUE TITLE
UI won't load, Connection Reset due to - qt.network.ssl: QSslSocket::startClientEncryption

### ISSUE THREAD

**Issue by ansred** [linuxserver/docker-qbittorrent#105]
## Expected Behavior
To load the UI as normal

## Current Behavior
UI won't load, Connection Reset due to - qt.network.ssl: QSslSocket::startClientEncryption

## Steps to Reproduce
It happens sometimes

## Environment
**OS:** Synology NAS
**CPU architecture:** x86_64
**How docker service was installed:**
Docker Package + Portainer Stack

## Docker logs
`qt.network.ssl: QSslSocket::startClientEncryption: cannot start handshake on non-plain connection`

It works fine after force restart for the container

Any idea why this happens, and how to stop it from happening that often?

**Comment by j0nnymoe** [comment]
This doesn't happen on a fresh install of the container. Do you have SSL enabled for the webui within qbittorrent?

**Comment by ansred** [comment]
@j0nnymoe  I do have it sitting behind nginx proxy manager, but no ssl installed on the webserver itself

**Comment by j0nnymoe** [comment]
Please provide more info about how you're deploying with portainer as we need to be able to see the environment variables you're using.

**Comment by ansred** [comment]
sure, here is the docker compose I used for my setup


```
---
version: '2.4'
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "container:gluetun"
    environment:
      - PUID=1029
      - PGID=100
      - TZ=America/Toronto
      - WEBUI_PORT=9080
    volumes:
      - /volume1/docker/qBittorrent/config:/config
      - /volume1/docker/qBittorrent/downloads:/downloads
    restart: unless-stopped
```

Network setup is going through another docker compose stack (gluetun) VPN container


```
---
version: '2.4'
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    environment:
      - PUID=1029
      - PGID=100
      - TZ=America/Toronto
      - VPNSP=private internet access
      - REGION=CA Ontario
      - OPENVPN_USER=############ #Change to YOUR Username
      - OPENVPN_PASSWORD=########### #Change to YOUR Password
    volumes:
      - /volume1/docker/gluetun/config:/gluetun
    ports:
      - 666:80 #heimdal-VPN
      - 4466:443 #heimdal-VPN
      - 9080:9080 #QBitTorrent Web-UI
      - 6881:6881 #QBitTorrent
      - 6881:6881/udp #QBitTorrent
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

```


Let me know if there is any other questions, it just happened again and I had to restart the container manually.
