### ISSUE TITLE
QBT Docker fails to start on Synology with "error while loading shared libraries: libQt5Core.so.5"

### ISSUE THREAD

**Issue by Webreaper** [linuxserver/docker-qbittorrent#129]
## Expected Behavior

QBT should start for the latest version.

## Current Behavior

QBT crashes with `error while loading shared libraries: libQt5Core.so.5` for any version newer than 4.3.2 on Synology DSM.
 
## Steps to Reproduce

Docker-compose:

```
 qbittorrent:
        image: linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - PUID=1024
            - PGID=101
            - TZ=Europe/London
            - UMASK=022
            - WEBUI_PORT=8090
        volumes:
            - /volume1/dockerdata/qbt/config:/config
            - /volume1/video/Downloads:/tvdownloads 
        restart: unless-stopped
```
Changing the image version to the following solves the issue.

```
        image: linuxserver/qbittorrent:14.3.2.99202101080148-7233-0cbd15890ubuntu18.04.1-ls110
```
## Environment
**OS:** DSM 6.2 and DSM 7.0
**CPU architecture:** x86_64
**How docker service was installed:** Provided as part of Synology DSM

## Command used to create docker container (run/create/compose/screenshot)

See above.
