### ISSUE TITLE
Not loading trackers - different behavior when vpn is in same compose file as qbittorrent

### ISSUE THREAD

**Issue by twopwood** [linuxserver/docker-qbittorrent#133]
## Expected Behavior
When adding magnet link, trackers should connect and file should start downloading.

## Current Behavior
Similar to #45, when I add a magnet link none of the trackers connect and the download stalls.  However, if i change the listening port and force reannounce, the download starts successfully.  Setting the listening port to randomize at startup doesn't help; the next time I start the container the problem persists.
The interesting thing is that this only occurs when connecting through a VPN in the same compose file using `network_mode: service:vpn`.  If I start the vpn in another compose file, and connect qbittorrent via `network_mode: container:vpn`, adding a magnet link works fine and the trackers connect.
Also, if I try another qbittorrent container (e.g. https://hotio.dev/containers/qbittorrent/) which is also using qbittorrent v4.3.7, it works correctly in either case.
I would be interested to see if anyone (with NordVPN or another VPN) can reproduce this issue.  Obviously I can switch to another qbittorrent container or configuration, but this one seems to work the best for me otherwise and I think if someone more knowledgeable looks at this they may find a bug that causes this issue in other situations.  I've put my compose files below but I'm not sure where to begin troubleshooting this since I am fairly new to Docker.  Thanks.

## Steps to Reproduce
1. Add magnet link

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:** apt; docker-compose

### Using `network_mode: service:vpn`
dc-combined.yaml:
```
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - USER=username
      - "PASS=password"
      - CONNECT=us8927  # keep consistent between tests
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - /tmp/docker-test/combined/config:/config
      - /tmp/docker-test/combined/downloads:/downloads
```
1. sudo docker-compose -f $PWD/dc-combined.yaml up
2. add magnet link to qbittorrent WebUI
3. torrent stalls
4. change listening port to random
5. Force reannounce torrent
6. Now torrent downloads

### Using `network_mode: container:vpn`
dc-vpn.yaml:
```
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - USER=username
      - "PASS=password"
      - CONNECT=us8927  # keep consistent between tests
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
```
dc-torrent.yaml:
```
version: "3"
services:
  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: container:vpn
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - /tmp/docker-test/torrent/config:/config
      - /tmp/docker-test/torrent/downloads:/downloads
```
1. sudo docker-compose -f $PWD/dc-vpn.yaml up
2. sudo docker-compose -f $PWD/dc-torrent.yaml up
3. add magnet link to qbittorrent WebUI
4. torrent downloads as expected

### Using alternate qbittorrent container
dc-combined-alt.yaml:
```
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - USER=username
      - "PASS=password"
      - CONNECT=us8927  # keep consistent between tests
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
  torrent:
    image: hotio/qbittorrent
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - /tmp/docker-test/combined-alt/config:/config
```
1. sudo docker-compose -f $PWD/dc-combined-.yaml up
2. add magnet link to qbittorrent WebUI
3. torrent downloads as expected
