### ISSUE TITLE
qbittorrent container doesn't always restart on reboot

### ISSUE THREAD

**Issue by Altycoder** [linuxserver/docker-qbittorrent#167]
**Expected Behavior**
qbittorrent container starts following server reboot as all my other containers do (20 or so).

NB: I have only recently started using gluetun as a docker based VPN - this issue persisted before I made that change.

**Current Behavior**
qbittorrent container only starts maybe 10-20% of the time and mostly does not

**Steps to Reproduce**
**Environment**
Arch with LTS kernel (5.15.x, amd64) docker installed from Arch repo

**Command used to create docker container (run/create/compose/screenshot)**
```
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/London
      - WEBUI_PORT=8085
    volumes:
      - <redacted path>:/config
      - <redacted path>:/downloads
#    ports: # ****these are specified in gluetun container instead***
#      - 6881:6881
#      - 6881:6881/udp
#      - 8085:8085
    depends_on:
      - gluetun
    restart: always #also tried "unless-stopped" and "on-failure"
```

**Docker logs**
There is nothing showing an error in the logs I can see via watchtower.  Is there another log location I can post from?
