### ISSUE TITLE
Sometimes requires login even if "Bypass authentication for clients in whitelisted IP subnets" is checked for 0.0.0.0/0

### ISSUE THREAD

**Issue by MrStarktastic** [linuxserver/docker-qbittorrent#168]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I have qBittorrent installed with the VueTorrent add-on (not sure if that's relevant). I wanted to disable authentication for it so that I could put Authelia behind the service and avoid a double login page.
The method described in the title worked for several months, but with the recent couple of updates I've noticed that it sometimes makes me type credentials after Authelia's successful login.

------------------------------

## Expected Behavior
qBittorrent's login page should not show up at all.

## Current Behavior
qBittorrent's login page shows up sometimes, but it's more consistent in incognito.
It doesn't matter what credentials I type - it lets me in, but that's annoying.

## Steps to Reproduce
1. Go to qBittorrent's URL in the browser
2. Login using Authelia (if required)
3. qBittorrent's login page shows up
4. Type any username+password to "login" for the second time

## Environment
**OS:** Debian Linux
**CPU architecture:** x86_64
**How docker service was installed:**
From the official Docker repo.

## Command used to create docker container (run/create/compose/screenshot)
Compose:
```
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
    networks:
      - upstream
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOCKER_MODS: arafatamim/linuxserver-io-mod-vuetorrent
    volumes:
      - ${BASE_MOUNT}/qbittorrent:/config
      - ${EXT_DRIVE_DOWNLOADS}:/data/downloads
```

## Docker logs
The logs don't say anything...
