### ISSUE TITLE
container stops working unexpectedly

### ISSUE THREAD

**Issue by Barney241** [linuxserver/docker-qbittorrent#170]
## Expected Behavior
should work 24/7

## Current Behavior
Qbittorent stops working randomly around 1 day since starting container. I couldnt find anything in the log files indicating whats wrong. Sometimes i had to remove container completely because docker failed to start or restart container.

I use gluetun to hide qbittorent behind vpn

## Command used to create docker container
```
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=114
      - PGID=122
      - TZ=Europe/Prague
      - WEBUI_PORT=8080
    volumes:
      - /home/barney/containers/serveros-containers/qbittorent_gluetun/qbittorent/config:/config
      - /media/torrents:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun"

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:

    volumes:
      - /home/barney/containers/serveros-containers/qbittorent_gluetun/gluetun/config:/gluetun
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
```
