### ISSUE TITLE
WebUI slows down and/or becomes unreachable when many torrents are active/queued

### ISSUE THREAD

**Issue by antonkvm** [linuxserver/docker-qbittorrent#175]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

WebUI should remain as responsive after adding many (~75) torrents as it is with only a handful (~5).

## Current Behavior

WebUI slows down considerably in all facets when many torrents are added:
- After opening WebUI, the list stays empty for at least several seconds before populating with the torrents.
- After clicking a torrent, the info section below takes at least 5 to 10 seconds to update.
- Requesting the WebUI in the browser may take very long, sometimes the request even times out.
- Opening settings or viewing stats takes several seconds at least.
- WebUI sometimes becomes unreachable.

The issue seems to only affect the WebUI, downloads appear to continue as normal.

## Steps to Reproduce

1. Create qBittorrent container with docker-compose.
2. Add a large number of torrents (~75).

## Environment
**OS:** Raspberry Pi OS 32 Bit Buster
**CPU architecture:** armhf/arm32v7
**How docker service was installed:** via Dockerhub
**Hardware:** Raspberry Pi 4B 4GBRAM, external Toshiba 2TB HDD as download destintion

## Command used to create docker container (run/create/compose/screenshot)

Via docker-compose:
```
version: '3.4'
services:
  vpn:
    container_name: vpn
    devices:
      - /dev/net/tun
    dns: 1.1.1.1
    environment:
      FIREWALL: ''
    volumes:
      - /home/pi/docker/openvpn:/vpn
    image: dperson/openvpn-client
    restart: unless-stopped
    cap_add:
      - net_admin
    networks:
      - default
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on: 
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8081
    volumes:
      - /home/pi/docker/qbittorrent_linuxserver:/config
      - /mnt/Toshiba2TB/downloads:/downloads
      - /mnt/Toshiba2TB/moviesAndStuff:/moviesAndStuff
    restart: unless-stopped
networks:
  default:
```

## Docker logs

```
chown: changing ownership of '/downloads/copyrighted material.mkv': Operation not permitted
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8081
```
