### ISSUE TITLE
qbittorrent container crashes and docker 

### ISSUE THREAD

**Issue by Jihad** [linuxserver/docker-qbittorrent#185]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Working normally

## Current Behavior

container suddenly becomes unresponsive, all other containers stop and Docker CLI (& engine stops working)

## Steps to Reproduce
On my machine, as simple as
1. compose up yml
2. open qbittorrent
3. download something via Sonarr
4. wait 1 minute

## Environment
Intel chip or Apple chip: Apple
Docker Desktop Version: v4.11.0
**OS:** macOS Version: 12.3.1 (21E258)
**CPU architecture:** Apple chip / M1
**How docker service was installed:**
From Docker website for Mac

## Command used to create docker container (run/create/compose/screenshot)

```
---
version: "2.1"
services:
  qbittorrentvpn:
    image: lscr.io/linuxserver/qbittorrent:latest #https://hub.docker.com/r/linuxserver/qbittorrent
    container_name: QB
    privileged: true
    environment:
      - PUID=501
      - PGID=20
      - TZ=Asia/Riyadh
      - WEBUI_PORT_ENV=8080
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /Users/jihad/MediaStudio/Configs/QBittorrent:/config
      - /Users/jihad/MediaStudio/Torrents:/downloads
    restart: unless-stopped
```

## Docker logs

Even Docker CLI becomes totally non responsive, and

## Context
I thought it might be an issue with Docker it self, but I tested every container I have (Sonarr, Radarr, Jackett) alone.. the only one causing this after running it is this.

Noting I removed the containers, all configs and started it again. Same thing.

The weird part that is starts downloading, making connections at first.
