### ISSUE TITLE
Memory leak with 4.4.5

### ISSUE THREAD

**Issue by BrodyStone21** [linuxserver/docker-qbittorrent#193]
I'm not sure how to debug this issue, or what exactly is causing it. I noticed I had some memory leaks occurring about a month ago. My system's memory usage would slowly increase over several days until eventually reaching 100% and requiring a reboot. 

Originally, I thought the issue was caused by either Sonarr or Radarr, since I had recently set them up. About a week ago, I realized qBittorrent is causing the issues, but I'm unsure if it's an issue with my settings, if I have too many torrents seeding, or something else. 

If anyone has any idea what could cause this, I would really appreciate some input. I've included my logs and docker-compose configuration below. I've also included all settings I thought would be applicable.

I'm seeding 440 torrents.

![image](https://user-images.githubusercontent.com/36679309/191992570-ab304e05-fbec-4a3c-8143-24d6b5bebbcd.png)
![image](https://user-images.githubusercontent.com/36679309/191992615-e42e3402-98e9-4048-a601-a7202bb6847b.png)
![image](https://user-images.githubusercontent.com/36679309/191992689-7ce37369-a1f9-4cd3-ab73-434f7ed5ccc9.png)
![image](https://user-images.githubusercontent.com/36679309/191992751-4680ba90-cb37-4c23-9b06-2309187a1f67.png)

```
version: '3'

networks:
  vpn_net:
    name: vpn_net
    external: true

services:
  vpn:
    container_name: vpn
    restart: unless-stopped
    image: linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 51820:51820/udp
      - 6595:6595
      - 6767:6767
      - 6789:6789
      - 7878:7878
      - 8075:8075
      - 8989:8989
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - INTERNAL_SUBNET=10.15.15.0
      - TZ=America/Indianapolis
    volumes:
      - /home/ubuntu/.config/wireguard:/config
      - /lib/modules:/lib/modules
    networks:
      vpn_net:
        ipv4_address: 172.18.0.2
  qbittorrent:
    container_name: qbittorrent
    restart: unless-stopped
    image: linuxserver/qbittorrent
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - WEBUI_PORT=8075
    volumes:
      - /home/ubuntu/.config/qbittorrent:/config
      - /mnt/WD_White/Media:/data
    network_mode: service:vpn
    depends_on:
      - vpn
```

```
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[custom-init] No custom files found, skipping...

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8075
[ls.io-init] done.
```

Output of `htop --sort=PERCENT_MEM`. Note, these numbers will slowly climb over time. 
![image](https://user-images.githubusercontent.com/36679309/191993269-297f8fc9-29f1-4032-97a9-8f44a41d4e39.png)
