### ISSUE TITLE
[BUG] SQLite database not working out of the box

### ISSUE THREAD

**Issue by SinTan1729** [linuxserver/docker-qbittorrent#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you turn on the option to use SQLite for resume data (in the advanced settings), the container won't start. It's solved easily by installing the package `qt6-qtbase-sqlite` inside the container.

### Expected Behavior

It should work. Ideally, the package should be preinstalled.

### Steps To Reproduce

1. Install version 5.4.1
2. Go to advanced settings
3. Change the resume data type to SQLite
4. Restart the container

### Environment

```markdown
- OS: AlmaLinux 9.1
- How docker service was installed: Distro's package manager
```

### CPU architecture

x86-64

### Docker creation

```yml
services:
...
(Setup for gluetun)
... 
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.5.1
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=8085
    volumes:
      - ./qbt-config:/config
      - /mnt/storage/Torrent:/downloads
    healthcheck:
      test: ping 1.1.1.1 -nqc 1 -W 4 >/dev/null 2>&1 || ping 8.8.8.8 -nqc 1 -W 4 >/dev/null 2>&1 || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    depends_on:
      gluetun:
        condition: service_healthy  
    labels:
      - deunhealth.restart.on.unhealthy=true
...
(Setup for networks)
...
```

### Container logs

```bash
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:
Driver not loaded Driver not loadedQSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:
Driver not loaded Driver not loadedQSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:
Driver not loaded Driver not loadedQSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:
Driver not loaded Driver not loadedQSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:
Driver not loaded Driver not loadedQSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:
Driver not loaded Driver not loadedQSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:
Driver not loaded Driver not loadedQSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:
```
