### ISSUE TITLE
[FEAT] 24-hour time and date

### ISSUE THREAD

**Issue by tordenflesk** [linuxserver/docker-qbittorrent#255]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Force/set 24-hour time and a sane date format.

### Reason for change

QBittorrent doesn't appear to follow system time and date format. Seems stuck in "American" 12-hour time and date format:
![image](https://github.com/linuxserver/docker-qbittorrent/assets/2136727/9b1b966c-c8ed-4592-9d30-b66b3008d83a)
```
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Oslo
      - WEBUI_PORT=8090
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:qbittorrent-regex
      - TP_THEME=nord
    volumes:
      - /Docker_Config/QBITTORRENT:/config
      - /srv/dev-disk-by-uuid-5c3c71b2-dce8-4967-95f4-eba3d293a511:/DATA01
    ports:
      - 8090:8090
      - 32323:32323
      - 32323:32323/udp
    restart: unless-stopped
```
