### ISSUE TITLE
[BUG] Unable to connect to WebUI

### ISSUE THREAD

**Issue by mayurrenr** [linuxserver/docker-qbittorrent#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the default 8080 port to access WebUI, firefox gives me "Unable to connect" error, edge gives "refused to connect' error.

If I remove qb and start another container for a different app using port 8080, this works fine (eg. stirling-pdf).

My setup currently is docker installed on debian 12 VM with only the qbittorrent container running via docker compose:

```
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent_data/config:/config
      - /data/mystorage/private/torrents:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    name: dockernet
    external: true
```

Additionally, I have added the following lines to the qbittorrent.conf file located in the config folder:

```
WebUI\CSRFProtection=false
WebUI\HostHeaderValidation=false
```

Finally, I have deleted the entire VM and reconfigured a new one, from scratch, and still unable to connect to WebUI. Other apps have all worked fine (NPM, cloudflared, portainer, stirling-pdf). Please note, all of these have now been removed in favour of troubleshooting qbittorrent.

Firewall/ufw disabled.
Ipv6 disabled.

### Expected Behavior

WebUI should load on server-local-ip:8080

### Steps To Reproduce

1. ESXi hypervisor
2. Debian 12
3. Docker via standard CLI instructions on official website
4. Qb as per above docker compose file

### Environment

```markdown
- OS: Debian 12
- How docker service was installed: CLI as per official guide
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent_data/config:/config
      - /data/mystorage/private/torrents:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    name: dockernet
    external: true
```

### Container logs

```bash
To control qBittorrent, access the WebUI at: http://localhost:8080

The WebUI administrator username is: admin
The WebUI administrator password was not set. A temporary password is provided for this session: XA83mHutz
You should set your own password in program preferences.
Connection to localhost (::1) 8080 port [tcp/http-alt] succeeded!
```
