### ISSUE TITLE
[BUG] <5.0.0 do not display # no columns>

### ISSUE THREAD

**Issue by rehack** [linuxserver/docker-qbittorrent#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

5.0.0 web ui cant show the index number in table title
![PixPin_2024-11-09_13-59-55](https://github.com/user-attachments/assets/4defb0b9-7666-4838-b5da-69fa2be60692)

### Steps To Reproduce

I have set up the display of index number columns, but it is not working.

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

``` yml
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=3809 # web端口
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - /mnt/media:/downloads
    ports:
      - 3809:3809 # web端口
      - 6881:6881 # TCP
      - 6881:6881/udp # UDP
    deploy:
      resources:
        limits:
          memory: 900M
    restart: unless-stopped
```

### Container logs

```bash
██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: 5.0.0-r2-ls361
Build-date: 2024-10-27T06:52:25+00:00
───────────────────────────────────────
    
[custom-init] No custom files found, skipping...
WebUI 将在内部准备不久后启动。请稍等…

******** 信息 ********
要控制 qBittorrent，请访问下列地址的 WebUI：http://localhost:3809
Connection to localhost (::1) 3809 port [tcp/*] succeeded!
[ls.io-init] done.
```
