### ISSUE TITLE
[BUG] Can't remove trackers from WebUI

### ISSUE THREAD

**Issue by nicolajkl** [linuxserver/docker-qbittorrent#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When removing a tracker URL from a torrent nothing happens. 
Editing works fine though. 

### Expected Behavior

The tracker URL should be removed. 
According to the issue linked below it should've been resolved in "current master" (3 weeks ago at the time of writing this):
https://github.com/qbittorrent/qBittorrent/issues/22039#issuecomment-2558014572

Which is why I suspect this is an LSCR issue. I tried to look for which version you're using in this container, but wasn't successful in finding that info. 

### Steps To Reproduce

1. Highlight a torrent
2. Go to the tracker tab in lower half of UI
3. Right click a tracker and click "Remove tracker"
4. Nothing happens

### Environment

```markdown
- OS: Debian Bullseye/Raspberry Pi OS lite 64 bit
- How docker service was installed: apt I think (don't remember/5 years ago or so)
```

### CPU architecture

ARMv8-A

### Docker creation

```bash
qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
    volumes:
      - /mnt/usb/config/qbittorent:/config
      - /mnt/usb/media:/media
      - /home/autobrr:/autobrr
    ports:
      - 4900:4900/tcp
      - 4900:4900/udp
      - 8080:8080/tcp
    restart: unless-stopped
    networks: 
      - docker_network
```

### Container logs

```bash
No entries in log when trying to remove trackers.
```

**Comment by sizeur** [comment]
I have the same problem. In the link you provide "https://github.com/qbittorrent/qBittorrent/issues/22039#issuecomment-2558014572" the comment said the problem is still present in  v5.0.3, which is the latest stable version: https://www.qbittorrent.org/news

![image](https://github.com/user-attachments/assets/33195141-4e45-435b-90f8-a95ffe6c3a4a)

The version I am using:
![image](https://github.com/user-attachments/assets/7bcde710-1693-45d3-80bc-e561ecc0314f)

So I believe the problem is not from linuxserver but it's from qbitorrent, we have to wait for the next stable release

**Comment by taw123** [comment]
Per my comment source qBit repo....

https://github.com/qbittorrent/qBittorrent/issues/22039#issuecomment-2569708030


Pro-ported to be fixed in current head but no build since 5.0.3 so only way to pick this up in via linuxserver's docker image is if they have a daily or test build train. Something I am getting to thee point of considering as I don't REALLY want to build myself and can't keep living with the jack I have tons of bogus trackers I need to purge from current torrents and of course can/'tt do that given the bug. Not complaining (1st world problem) :)

**Comment by sizeur** [comment]
Well, instead of building my own image i rather rollback to 5.0.2... 
```
root@localhost: cat /qbittorrent/docker-compose.yaml
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent**:5.0.2**
[...]
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false" # Prevent watchtower to update container (if needed)
root@localhost:/qbittorrent$ sudo docker-compose down
root@localhost:/qbittorrent$ sudo docker-compose up -d
```
Tracker can be deleted again without problems, but I need to manually update container in the future :/
