### ISSUE TITLE
[BUG] WebUI config can not be saved

### ISSUE THREAD

**Issue by blankhang** [linuxserver/docker-qbittorrent#395]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

can save anything at all
please check it

![Image](https://github.com/user-attachments/assets/d47a54e5-4b28-455e-ac9c-4cbc923587be)

### Expected Behavior

saved configs normally

### Steps To Reproduce

```yml
version: "3"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    restart: always
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=19900
      - TORRENTING_PORT=19901
    volumes:
      - ./config:/config
      - /share/CACHEDEV1_DATA/homes/blank/Downloads/bt:/downloads
    ports:
      - "19900:19900"
      - "19901:19901"
      - "19901:19901/udp"
```

### Environment

```markdown
- OS:QNAP docker
- How docker service was installed:
[blank@QNAP ~]$ docker version
Client:
 Version:           27.1.2-qnap4
 API version:       1.46
 Go version:        go1.21.13
 Git commit:        d46fd47
 Built:             Mon Nov  4 10:37:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.2-qnap4
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       7d28525
  Built:            Mon Nov  4 10:36:08 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose up -d
```

### Container logs

```bash
qbittorrent1-1  | [migrations] started
qbittorrent1-1  | [migrations] no migrations found
qbittorrent1-1  | usermod: no changes
qbittorrent1-1  | ───────────────────────────────────────
qbittorrent1-1  | 
qbittorrent1-1  |       ██╗     ███████╗██╗ ██████╗
qbittorrent1-1  |       ██║     ██╔════╝██║██╔═══██╗
qbittorrent1-1  |       ██║     ███████╗██║██║   ██║
qbittorrent1-1  |       ██║     ╚════██║██║██║   ██║
qbittorrent1-1  |       ███████╗███████║██║╚██████╔╝
qbittorrent1-1  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
qbittorrent1-1  | 
qbittorrent1-1  |    Brought to you by linuxserver.io
qbittorrent1-1  | ───────────────────────────────────────
qbittorrent1-1  | 
qbittorrent1-1  | To support LSIO projects visit:
qbittorrent1-1  | https://www.linuxserver.io/donate/
qbittorrent1-1  | 
qbittorrent1-1  | ───────────────────────────────────────
qbittorrent1-1  | GID/UID
qbittorrent1-1  | ───────────────────────────────────────
qbittorrent1-1  | 
qbittorrent1-1  | User UID:    911
qbittorrent1-1  | User GID:    911
qbittorrent1-1  | ───────────────────────────────────────
qbittorrent1-1  | Linuxserver.io version: 5.1.1-r0-ls401
qbittorrent1-1  | Build-date: 2025-06-29T06:58:49+00:00
qbittorrent1-1  | ───────────────────────────────────────
qbittorrent1-1  |     
qbittorrent1-1  | [custom-init] No custom files found, skipping...
qbittorrent1-1  | WebUI will be started shortly after internal preparations. Please wait...
qbittorrent1-1  | 
qbittorrent1-1  | ******** Information ********
qbittorrent1-1  | To control qBittorrent, access the WebUI at: http://localhost:19900
qbittorrent1-1  | The WebUI administrator username is: admin
qbittorrent1-1  | The WebUI administrator password was not set. A temporary password is provided for this session: XKUwELaJw
qbittorrent1-1  | You should set your own password in program preferences.
qbittorrent1-1  | Connection to localhost (::1) 19900 port [tcp/*] succeeded!
qbittorrent1-1  | [ls.io-init] done.
```
