### ISSUE TITLE
QBittorrent stuck at downloading metadata

### ISSUE THREAD

**Issue by MacGyver27** [linuxserver/docker-qbittorrent#45]
Hey,

When adding new magnet torrents via webui they get stuck in "downloading metadata"..  Sometimes they eventually recovers.. in minutes , hours or days. However sometimes they don't.
Thought it could be my local DNS resolution server on host, but no. Logs don't say much as well.
Anyway port 6881 is allowed on host.

BTW on the same LAN using qb on win and no issues whatsoever.. same magnet starts immediately at full speed.

Host: Debian Buster
Image: latest

Docker-Compose:
```
version: "3.7"

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent.528
    restart: always
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 52880:52880
    volumes:
      - $PWD/config:/config
      - /lvm/raid/private/media/.downloads:/downloads
    environment:
      - TZ=Europe/Prague
      - PUID=1000
      - PGID=994
      - UMASK_SET=022
      - WEBUI_PORT=52880
    labels:
      - traefik.enable=true
      - traefik.port=52880
      - traefik.frontend.entryPoints=https
      - traefik.frontend.rule=Host:qb.example.com
      - traefik.backend=qbittorrent.528
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true

networks:
  default:
    name: qbittorrent.528
```

However googling around found this issue: https://github.com/qbittorrent/qBittorrent/issues/5006#issuecomment-201619521 and it seems to be the case.
Another reddit thread: https://www.reddit.com/r/qBittorrent/comments/7x03yk/stuck_on_downloading_metadata_on_one_pc/
And from linustechtips forum:
![image](https://user-images.githubusercontent.com/6546231/55811307-384d9880-5ae9-11e9-9cd2-df1c8f0b23b4.png)

**So just by changing the port it starts immediately working again. They say this needs to be done on every startup..**

Any ides how to address this for the future? Thanks
