### ISSUE TITLE
Unable to connect to Jackett via UI

### ISSUE THREAD

**Issue by marky7** [linuxserver/docker-qbittorrent#73]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Hello, I'm actualy unable to connect docker-qbittorrent to Jackett.

I tried first with official qbittorrent client and it worked but it doesn't with docker-qbittorrent. "Jackett" is launched (https://hub.docker.com/r/linuxserver/jackett/) with default configurations on localhost (https://github.com/Jackett/Jackett).

------------------------------

## Expected Behavior
The results of the research should appear in the list

## Current Behavior
error message : "Jackett connection error! Click 'Go to description button to open help. Configuration file: ..."

## Steps to Reproduce
1. Launch jackett with default configurations via docker-compose (https://hub.docker.com/r/linuxserver/jackett/), add some random indexers, and ensure that it works with manual research.
2. Launch officiel qbitorrent client, add default plugin and check that connection works well for Jackett.
3. Now try with docker-qbittorrent by creating docker-compose.yml file and insert this code inside. Replace [my_path] and following path by the location of your own folders.

```
version: "2.1"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - [my_path]/qbittorent/config:/config
      - [my_path]/qbittorent/downloads:/downloads
      - [my_path]/qbittorent/data-qBittorrent:/config/data/qBittorrent
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

```
4. docker-compose up, the app is launched.
5. A volume is created on data/qBittorent, get the "API key" displayed in Jackett (http://localhost:9117/UI/Dashboard) and insert it inside your config file thanks to the volume data-qBittorrent ([my_path]/qbittorent/data-qBittorrent/nova3/engines/jackett.json

```
{
    "api_key": "nrroibkuhiy3rfs7oz8bkp33740d0day",
    "tracker_first": false,
    "url": "http://127.0.0.1:9117"
}

```
6. Try to do a research on plugin Jackett via docker-qbittorrent and get the resulting "Jackett connection error! Click 'Go to description button to open help. Configuration file: ..."

## Environment
OS: Ubuntu 18.04
CPU architecture: amd64      

## Docker logs

No logs from jackett
No logs from qBitorrent

Thank you for your help

**Comment by j0nnymoe** [comment]
Don't use localhost/127.0.0.1. You need to use your server ip or the container's IP (or name if its on the same docker network.)

**Comment by marky7** [comment]
Effectively, it works really well now :)

File : docker-compose.yml
```
version: "2.4"

services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "./jackett/config:/config"
      - "./downloads:/downloads"
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - torrent

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - "./qbittorent/config:/config"
      - "./downloads:/downloads"
      - "./qbittorent/data-qBittorrent:/config/data/qBittorrent"
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
    networks:
      - torrent

networks:
  torrent:
```

File : qbittorent/data-qBittorrent/nova3/engines/jackett.json
```
{
    "api_key": "eukbja5uuhon4ij6ei5v8x4vl5rjl03u",
    "tracker_first": false,
    "url": "http://jackett:9117"
}
```

Thank you a lot for your reactivity.
