### ISSUE TITLE
Connection error while using SOCKS5 proxy in QBittorent and using research plugins

### ISSUE THREAD

**Issue by marky7** [linuxserver/docker-qbittorrent#74]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Hello, I use a connection proxy of type SOCKS5 in QBittorent. However, I get a connection error when I try to do a research on Jackett v0.16. It works without using the connection proxy on QBittorent. 

The server proxy works well for the download/upload inside QBittorent and the research in Jackett works well without the proxy. 

I launch QBittorent and Jackett thanks to a docker-compose file.

I have tried to add RUN_OPTS=-chttpclient2 option as mentionned in issue : https://github.com/Jackett/Jackett/issues/4862 but it is just an option for SOCKS5 proxy inside jacket and using SOCKS5 proxy inside Jackett works correctly.

Edit : No one of other research plugins is working with the SOCKS5 proxy on QBittorent. They work only without the proxy.

------------------------------

## Expected Behavior
The results of the research should appear in the list

## Current Behavior
error message : "Jackett connection error! Click 'Go to description button to open help. Configuration file: ..."

## Steps to Reproduce

1/ There is my docker-compose.yml

```
version: "2.2"

services:

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Europe/Paris
      - RUN_OPTS=-chttpclient2
    volumes:
      - "./jackett/config:/config"
      - "./downloads:/downloads"
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - torrent

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Europe/Paris
      - UMASK_SET=022
      - WEBUI_PORT=8081
    volumes:
      - "./qbittorent/config:/config"
      - "./downloads:/downloads"
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8081:8081
    restart: unless-stopped
    networks:
      - torrent

networks:
  torrent:

```
2/ Configure connection with Jackett, add indexes and test research on Jackett.
3/ Configure the QBittorrent connection on SOCKS5 proxy with a vpn server.
4/ Test the download with new IP.
5/ Try the research on Jackett and get the resulting "Jackett connection error! Click 'Go to description button to open help. Configuration file: ..."

## Environment
OS: Ubuntu 18.04
CPU architecture: amd64      

## Docker logs

No logs from jackett docker
No logs from qBitorrent docker

Thank you for your help
