### ISSUE TITLE
Radarr/Sonarr/Lidarr won't connect after recent upgrade

### ISSUE THREAD

**Issue by MacGyver27** [linuxserver/docker-qbittorrent#82]
Hi,

After recent upgrade none of the Sonarr/Radarr/Lidarr will connect with your qbittorent container. I did no configuration changes just performed new docker image pull and it stopped working.

Error log from console:
```
sonarr | [v2.0.0.5344] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings. ---> System.Net.WebException: Error: ConnectFailure (Connection timed out): 'https://192.168.255.11:52880/api/v2/app/webapiVersion' ---> System.Net.WebException: Error: ConnectFailure (Connection timed out) ---> System.Net.Sockets.SocketException: Connection timed out
sonarr |   at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in <91935ad653254a93b9d73a9f8f2f7a2d>:0
sonarr |   at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in <91935ad653254a93b9d73a9f8f2f7a2d>:0
sonarr |   at System.Net.Sockets.SocketTaskExtensions+<>c.<ConnectAsync>b__2_1 (System.IAsyncResult asyncResult) [0x00006] in <91935ad653254a93b9d73a9f8f2f7a2d>:0
sonarr |   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in <254335e8c4aa42e3923a8ba0d5ce8650>:0
sonarr | --- End of stack trace from previous location where exception was thrown ---
plex.529.sonarr.82 |
sonarr |   at System.Net.WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x0019b] in <91935ad653254a93b9d73a9f8f2f7a2d>:0
sonarr |    --- End of inner exception stack trace ---
sonarr |   at System.Net.WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x00217] in <91935ad653254a93b9d73a9f8f2f7a2d>:0
sonarr |   at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x000cc] in <91935ad653254a93b9d73a9f8f2f7a2d>:0
sonarr |   at System.Net.WebOperation.Run () [0x0009a] in <91935ad653254a93b9d73a9f8f2f7a2d>:0
sonarr |   at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x00094] in <91935ad653254a93b9d73a9f8f2f7a2d>:0
sonarr |   at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <91935ad653254a93b9d73a9f8f2f7a2d>:0
sonarr |   at System.Net.HttpWebRequest.GetResponse () [0x00016] in <91935ad653254a93b9d73a9f8f2f7a2d>:0
sonarr |   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x0011b] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:82
sonarr |    --- End of inner exception stack trace ---
sonarr |   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x001ca] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:113
sonarr |   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x0003c] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:35
sonarr |   at NzbDrone.Common.Http.HttpClient.ExecuteRequest (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookieContainer) [0x0007e] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:121
sonarr |   at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00008] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:57
sonarr |   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.IsApiSupported (NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x00019] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:36
sonarr |    --- End of inner exception stack trace ---
sonarr |   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.IsApiSupported (NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x0006b] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:58
sonarr |   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.FetchProxy (NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings) [0x00000] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:75
sonarr |   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector+<>c__DisplayClass6_0.<GetProxy>b__0 () [0x00000] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:70
sonarr |   at NzbDrone.Common.Cache.Cached`1[T].Get (System.String key, System.Func`1[TResult] function, System.Nullable`1[T] lifeTime) [0x0006a] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Cache\Cached.cs:81
sonarr |   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxy (NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentSettings settings, System.Boolean force) [0x00049] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:70
sonarr |   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.TestConnection () [0x00000] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:227
plex.529.sonarr.82 |
sonarr | [Warn] NzbDroneErrorPipeline: Invalid request Validation failed:
sonarr |  -- Unknown exception: Failed to connect to qBittorrent, check your settings.
```

Credentials are correct and they work via webUI. I dont really understands why it times-out :/

WebUI is accessible as before. Just something wrong on the API level..

I wanted to try older version but was so confused with your tags. Please list in your image description how to rollback e.g. to 4.2.0 or 4.1.1 because your tags make no sense to me and I cannot see any correlation..

Thanks, Michal

**Comment by MacGyver27** [comment]
Soo when trying to access qbittorrent "locally" via `qbittorrent:443` it works but not anymore via FQDN `qb.plex.example.com:443`.. I have other reasons to access it this way (VPN).. really clueless what went wrong in here. Two days ago it still worked.

```yml
  qbittorrent:
    container_name: plex.529.qbittorrent.99
    image: linuxserver/qbittorrent
    restart: always
    expose:
      - 52999
    volumes:
      - $PWD/qbittorrent/config:/config
      - /media/.downloads:/downloads
    environment:
      - TZ=Europe/Prague
      - PUID=1000
      - PGID=994
      - UMASK_SET=022
      - WEBUI_PORT=52999
    labels:
      - traefik.enable=true
      - traefik.port=52999
      - traefik.frontend.entryPoints=https
      - traefik.frontend.rule=Host:qb.plex.example.com
      - traefik.backend=plex.529.qbittorrent.99
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
```
