### ISSUE TITLE
qbittorrent  don't download into directory outside container

### ISSUE THREAD

**Issue by schel4ok** [linuxserver/docker-qbittorrent#89]
I installed qbittorrent on Synology Docker application.
And I want all my downloads to be in directory /volume2/Downloads
------------------------------
Here is my docker-compose file. With this setup torrents will not work. But if I uncomment string `./downloads:/downloads` and comment string `/volume2/Downloads:/downloads` and restart container then all torrents will start immediately.

```
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8068
    volumes:
      - ./qbittorrent:/config
      #- ./downloads:/downloads
      - /volume2/Downloads:/downloads
    ports:
      - 6882:6881
      - 6882:6881/udp
      - 8068:8068
```
